日付による残業貯金除外機能の追加 Issue/#1
nakashima-takeo/KoT-plus pull request #2
Opened 2024-10-10 16:38 UTC by nakataharuma

## 概要
残業貯金として計算**しない**日付を指定できるように
ポップアップから`10/01,10/03`のように入力することで指定が可能

## 実装したこと
- 労働日数などと同様に、ポップアップに日付を書き込みストレージへ保存する仕組みを実装
- 日別のテーブルレコードを扱うクラスである`TableRecordByDate`クラスの実装
  - 日別のテーブルレコードから労働合計や日付などの値を取得する関数を集約
- `労働合計`を合計する処理にて、指定された日付と一致した場合、計算しない処理を実装

## 変更結果
1. 日付を何もしていない状態では、残業貯金が`2.15`となっている
![スクリーンショット 2024-10-11 1 13 56のコピー](https://github.com/user-attachments/assets/ddf00677-6b19-45e7-b807-ac89ab6c70bd)

2. `10/04,10/09`の2日間を除外する日付として指定し、残業貯金が`2.15`に変化。除外指定が聞いたことが確認できた。
![スクリーンショット 2024-10-11 1 09 44](https://github.com/user-attachments/assets/635fa71b-064b-49a9-b259-3be091fa2731)

## 実装において補足したいこと
### 残業貯金を計算するこちらのコードブロックについて
https://github.com/nakashima-takeo/KoT-plus/blob/49e9d4dfe024f7001e55b0c69fa78e7c0e4843fa/content.js#L238-L252

日付の取得と同様に、労働合計を取得する処理も`TableRecordByDate`クラスへ集約したため、コード全体が書き換わっている

### コード全体のスタイルについて
クラス・関数の場所や、変数に使用する名前は既存のコードを見ながら合わせた（つもり）

### ストレージへの保存処理について
Chrome APIについて理解が足りていなく、雰囲気で実装したのでバグがあるかもしれない
（今のところ問題なく動作しているように見える）

## 実装していないこと
- 日付のフォーマットが正しくない場合にユーザーへ伝える処理

## レビューして欲しいところ
- より良いネーミング
- より良いコード
- コメントが欲しい部分

## 注意事項
特になし

##

2024-10-13 18:05 UTC, nakashima-takeo commented
対応するissueを紐づけておきました。
Pull Request をマージした際に自動で issue も閉じられるので、今後は紐付けると良いでしょう。

2024-10-13 18:08 UTC, nakashima-takeo commented
issue と 紐づけておきました。

紐づけると、 Pull Request がマージされた際に自動で issue もクローズされるので、今後はメンションするよりも紐付けた方が良いでしょう。

2024-10-13 21:29 UTC, nakashima-takeo commented
実装にはパッと見だとバグはなさそうです。
また、コミットメッセージも問題ないように思います。

2024-10-13 21:58 UTC, nakashima-takeo commented
改善してくれたコードについてもレビューしました。
レビューの内容はこの後に書いておきます。

なのですが、実際に実装された機能を見て思うところがありましたので、そこについて言及しようと思います。
もっと早く言えよと思うかもしれません。申し訳ないです。



現状のこの機能だと、
1. 設定画面を見なければどの日付が無効化されているのかが分からない。
2. 自分で解除しない限り無効化されたままである

という仕様により、「無効化した時は（申）という表示があったから無効化したことを覚えていたけれど、申請が通った後はすっかり無効化していたことを忘れてしまい勤務時間が足りなくなった」というような悲劇が起こりそうだなと考えています。


解決策としてはいくつか考えられると思っていて、

1. 単純に、無効化されている行に印をつける
2. 申請している間は行自体が無効化されるようにする
3. 修正後の勤務時間（正しい勤務時間）を入力できる列を設ける

パッと思いつくのはこれくらいですかね。

1. 実装は簡単ですが、「印」がなんなのかを伝えるのが難しいかも？結局人力で設定を変更する必要があるので面倒。また、結局毎回計算をすることから逃れられないので面倒。
2. 却下。問題が多すぎる。
3. 使用する側としてはおそらく一番便利な方法。実装は面倒かも？

私が実装するなら3ですかね。もっと良い方法があればそれがいいけど。

というわけで、もう一度考えてみてもらえると嬉しいです。
実装してもらった後にこんなこと言って申し訳ない。

2024-10-13 22:00 UTC, nakashima-takeo requested changes
以下の基準でレビューをしました！
確認よろしくお願いします。

- must: 変更必至。エラーなど。
- should: ほぼほぼ変更した方が良いと考えられる点。公式で推奨の書き方があるなど。
- suggest: 客観的にみて変更した方が良いと考えられる点。他に変えなくて良い理由などが無ければ変えてください。
- In my opinion: 個人的に気になる点。理由は無くとも変更はしなくて良いです。
- comment: コメント。

2024-10-13 22:00 UTC, nakashima-takeo commented on content.js
> +
![suggest](https://img.shields.io/badge/review-suggest-success.svg)
多分letにしなくても表現できるから、そうした方が良いのではないか。
個人的には、使わなくていいletはなるべく使わない方が良いと考えているためです。

```suggestion
// 除外する日付を取得
async function getNotCalDatesForWorkingTime() {
  const value = await chrome.storage.sync.get(['notCalDatesForWorkingTime']);

  // nullだった場合、空文字列を代入する
  const notCalDateText = value?.notCalDatesForWorkingTime || '';

  const NotCalForWorkTimeDateTexts = notCalDateText ? notCalDateText.split(',') : [];
  return NotCalForWorkTimeDateTexts;
}

```

2024-10-13 22:00 UTC, nakashima-takeo commented on content.js
> +    isNotCal = false;
![should](https://img.shields.io/badge/review-should-success.svg)
letがついていないと、スコープ内で二重定義してもエラーが出ない。
また、どこで定義されているのかを調べるために検索をすることになったので、つけるべき。

```suggestion
    let isNotCal = false;
```

2024-10-13 22:00 UTC, nakashima-takeo commented on content.js
> +    }
![In my opinion](https://img.shields.io/badge/review-In_my_opinion-yellow.svg)
この部分の表現が冗長で気になるかな。
setでhasとかを使うと数行で書ける気がします。

このコードでは問題ないけど、setだとO(1)で判定できるから、一般的にもsetを使用した方がいいかな。

2024-10-13 22:00 UTC, nakashima-takeo commented on content.js
> +}
![suggest](https://img.shields.io/badge/review-suggest-success.svg)
せっかく書いてくれてありがたいのだけれど、現状ではこのクラスの必要性が分からないです。
このクラスによって複雑さが低減していたり、関数が集約されている気がしないのですが、どうでしょうか？

私の目が節穴説や、今後このクラスに責任を委譲していくから将来的には大丈夫説もあると思うので、返答をお待ちしています。

2024-10-13 22:37 UTC, nakashima-takeo commented
![must](https://img.shields.io/badge/review-must-red.svg)
manifest.json の version のマイナーバージョンを一つ上げないといけないですね。
version 1.2.0 に書き換える必要があります。

2024-10-14 08:15 UTC, nakataharuma commented
@nakashima-takeo 
丁寧なレビュー頂き、ありがとうございます！
Issueへの関連付けやコードレビューなど細かい部分も意見を頂けて、勉強になります。

2024-10-14 08:52 UTC, nakataharuma commented
> 現状のこの機能だと、
> 
> 1. 設定画面を見なければどの日付が無効化されているのかが分からない。
> 2. 自分で解除しない限り無効化されたままである
> 
> という仕様により、「無効化した時は（申）という表示があったから無効化したことを覚えていたけれど、申請が通った後はすっかり無効化していたことを忘れてしまい勤務時間が足りなくなった」というような悲劇が起こりそうだなと考えています。

## 言及されている日付を無効化したことを忘れてしまう可能性について
同じ意見です。
レビューして頂いて気づきましたが、確かに現在のまま追加してしまうと危うい機能だなと感じました。

## 解決策
> 3. 修正後の勤務時間（正しい勤務時間）を入力できる列を設ける
> 私が実装するなら3ですかね。もっと良い方法があればそれがいいけど。

解決策の提案ありがとうございます。
こちらの方法であれば、無効化したことを忘れてしまう可能性もないですね。
操作体験としてもシンプルなので、私も賛成です！

また追加の機能として、正しい勤務時間を入力した後、間違っている値である労働合計にsタグで横線を追加することを考えました。
**入力した値が反映されたこと**をより認識しすいなと考えたためです。

イメージ↓
![image](https://github.com/user-attachments/assets/77636675-e1ff-4b86-92fa-e9866de1901c)
8.15:  間違っている値、申請が認定されないまま計算されている勤務時間
6.30: 正しい値、ユーザー側が把握している勤務時間

具体的な実装方法については考え中です。
プルリクエストで追加した部分を活用せず、1から書いてしまっても良いかなと考えています。

2024-10-14 08:54 UTC, nakataharuma commented on content.js
> +
> value?.notCalDatesForWorkingTime || ''

こんなシンプルな書き方があるんですね、初めて知りました。
letでの変数宣言についてモヤモヤしていたので助かります。

2024-10-14 09:14 UTC, nakataharuma commented on content.js
> +}
クラスとして実装した意図としては、
今回労働合計の値だけでなく新たに日付の値を取得する必要があり、どちらも日別のtr要素を参照していたため、集約した方が良いと考えました。
将来的にも、日別で何らかの値を取得することや処理を行うということが十分に考えられたためです。

```js
return this.trElement.querySelector(`td.${className}`);
```

またこのように、実際に値として利用するpタグの値ではなくtr要素を返しているのは、
列ごとにpタグが存在しなかったり、pタグにネストされた要素が入っているなどバラバラであったためです。

ただ、これらは先読みのし過ぎで冗長すぎるかなとも考えています。
複雑さを低減するためにも、より具体的な値を返すクラスとした方がよろしいでしょうか？

こちらについて、もしご意見頂けたら嬉しいです。

2024-10-14 16:01 UTC, nakashima-takeo commented
わかりやすくて良いと思います。

2024-10-14 21:57 UTC, nakashima-takeo commented on content.js
> +}
読む際に、少し困惑したので、現状としてはまだクラスとして実装しなくていいかなと考えております。
理由をいくつか挙げておきます。

1. 現状ではクラスとすることによる複雑さ低減のメリットよりも、クラスが増えたことによる複雑さの方が上回るように見える。
YAGNI原則に従うとまだかなと思う次第です。クラスをなくしてコードに直接書いてもそんなに複雑にならないように見えます。

2. なぜ日別のレコードだけをクラス化したのかが分からない。
まず、やっていることは「QuerySelectorを使っていてそのままのコードでは何をやっているかが分からない所に関数名という形で名前を付けた」ということだと認識しています。
そうだとすると、ここのqueryselectorだけが名付けられた理由が腑に落ちません。他にもデータをとってきている場所は数多あって、それら全体で一つのクラスとするなら納得もいくのですが。
詰まることろ、なんでここだけクラス化したんだろう？という疑問が生じるという話です。

2025-12-22 05:53 UTC, closed without merging